any-resumed should not affect available space on page when not rendered
brailleapps/dotify.formatter.impl pull request #100
Opened 2019-04-17 15:01 UTC by bertfrees

2019-06-21 14:15 UTC, bertfrees commented
I have rebased this onto master. See the corresponding commit in https://github.com/brailleapps/dotify.formatter.impl/compare/master...sbsdev:super/sbs.

2019-08-05 08:21 UTC, PaulRambags requested changes

2019-08-05 08:21 UTC, PaulRambags commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
It seems that you can now have an `anyTransitionText` that has a positive height AND `anyHeight` = 0. That is strange.
Should the extra condition be put one line earlier? I mean this:

```
List<RowGroup> anyTransitionText = transitionContent.isPresent()
                   && !(transitionContent.get().getType()==TransitionContent.Type.RESUME && isFirst))
		?new RowGroupDataSource(master, bc, transitionContent.get().getInAny(), BreakBefore.AUTO, null, cd).getRemaining()
		:Collections.emptyList();
float anyHeight = height(anyTransitionText, true);

```

2019-08-05 09:19 UTC, bertfrees commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
Yes, that would be better. Then the `if (transitionContent.get().getType()==TransitionContent.Type.RESUME  && !isFirst)` below can also be changed.

2019-08-06 06:43 UTC, kalaspuffar commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
This might be a choice that is common in the code base but I usually prefer to write code that first sets the else case and then use an if statement to override. Using onliners to set values when you use have conditions is a code smell IMHO. Either I create a boolean with an expressive name or if statements.

```
float anyHeight = 0
if (
    transitionContent.isPresent() && 
    !(transitionContent.get().getType() == TransitionContent.Type.RESUME && isFirst)
) {
    anyHeight = height(anyTransitionText, true);
}
```

Can still be an artistic choice to use either or and in this case the oneliner is not extreme so it could be a viable choice.

Spacing close to equal signs and other operators (except for not :) ) could also improve readability IMHO.

2019-08-06 13:40 UTC, bertfrees commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
Ah I see. Yeah, I also don't do that very often either, but am also not really against it.

I do try to avoid adding many variables unless it makes sense, so in this case I would prefer an if statement. I would probably put the `anyHeight = 0` inside the `else` though. Personal preference.

Regarding the spaces around `==`: yes I normally always do that, but in this case I was just trying to copy the style of the code around it.

Should we be discussing these kind of style issues at this point anyway? Shouldn't we instead be expanding the wiki or the CONTRIBUTING file?

2019-08-07 08:26 UTC, kalaspuffar commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
Hi @bertfrees 

I think we can skip my suggestions for this pull request as they are more of a style suggestion and we have not any clear way to go here. So to proceed we can keep it as is.

When do you expect to do the requested changes from @PaulRambags or should these also be skipped for this pull request?

Best regards
Daniel

2019-08-07 08:28 UTC, bertfrees commented on src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
> +					: 0;
Yes I'll get to that tomorrow or Friday. Working on the documentation PR now.

2019-08-08 16:02 UTC, PaulRambags approved these changes

2019-08-08 16:04 UTC, PaulRambags requested changes
The build fails

2019-08-08 16:13 UTC, bertfrees commented
Rebased.

2019-08-09 07:03 UTC, kalaspuffar approved these changes

2019-08-09 07:49 UTC, PaulRambags approved these changes

2019-08-09 18:08 UTC, kalaspuffar commented
Hi @bertfrees and @PaulRambags 

This PR is ready for merge. I've ran the tests and all seems green. So if you don't have any objections I'll merge it when I'm back in the office on Monday.

Great work.

Best regards
Daniel

2019-08-12 05:05 UTC, merged